
package calculatorapp;


import java.math.*;


public class CalculatorApp extends javax.swing.JFrame {

   private double total1=0.0;
   private double total2=0.0;
   private double total3=0.0;
   private char math_operator;
   private double fact=1.0;
  private String str;
    public CalculatorApp() {
           
        initComponents();
        pnt.setToolTipText("(.)");
         b1.setToolTipText("(1)");
         b2.setToolTipText("(2)");
         b3.setToolTipText("(3)");
         b4.setToolTipText("(4)");
         b5.setToolTipText("(5)");
         b6.setToolTipText("(6)");
         b7.setToolTipText("(7)");
         b8.setToolTipText("(8)");
         b9.setToolTipText("(9)");
         b0.setToolTipText("(0)");
         add.setToolTipText("(+)");
         sub.setToolTipText("(-)");
         mul.setToolTipText("(x)");
         div.setToolTipText("(/)");
         CE.setToolTipText("Cancel");
         sin.setToolTipText("sin()");
         cos.setToolTipText("cos()");
         tan.setToolTipText("tan()");
         pow.setToolTipText("(x)2");
          equals.setToolTipText("(=)");
          log.setToolTipText("(log)");
          fac.setToolTipText("(! ");
          Sqrt.setToolTipText("(Root)");
          XpowY.setToolTipText("(x^y)");
        }
    private void getOperator(String btnText)
    {
    math_operator= btnText.charAt(0);
    if(btnText.charAt(0)=='s')
    { 
       total1=total1+Double.parseDouble(display.getText());
       display.setText("Sin"+"("+total1+")");
     
    }
else  if(btnText.charAt(0)=='c')
    { 
       
     total1=total1+Double.parseDouble(display.getText());
    display.setText("Cos"+"("+total1+")");}
else  if(btnText.charAt(0)=='t')
    { 
        total1=total1+Double.parseDouble(display.getText());
    display.setText("tan"+"("+total1+")");}
else  if(btnText.charAt(0)=='x')
    { 
        
       total1=total1+Double.parseDouble(display.getText());
    display.setText("("+total1+")"+"2");}
else  if(btnText.charAt(0)=='l')
    { 
        
        total1=total1+Double.parseDouble(display.getText());
    display.setText("Log"+"("+total1+")");}
else  if(btnText.charAt(0)=='X')
    { 
        total2=0.0;
        total1 = total1 + Double.parseDouble( display.getText( ) ) ;
   display.setText("");
    }
else  if(btnText.charAt(0)=='S')
    { 
         total1=total1+Double.parseDouble(display.getText());
    display.setText("Sqrt"+"("+total1+")");
       }
else  if(btnText.charAt(0)=='n')
    { 
        
        total3=total3+Double.parseDouble(display.getText());
        display.setText(total3+"!");
       factorial(total3);
      
    }
else 
        
    {
        total1 = total1 + Double.parseDouble( display.getText( ) ) ;
   display.setText("");}
   
     
    }
    private void factorial(double total)
    {
     int   total4=(int)total;
    for(int i=total4;i>=1;i--)
    {
     double  j=(int)i;
    fact=fact*j;
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        CE = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        div = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        pow = new javax.swing.JButton();
        pic = new javax.swing.JLabel();
        XpowY = new javax.swing.JButton();
        fac = new javax.swing.JButton();
        pnt = new javax.swing.JButton();
        add = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        log = new javax.swing.JButton();
        Sqrt = new javax.swing.JButton();
        display = new javax.swing.JTextField();
        PI = new javax.swing.JButton();
        on = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        Calculator = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("File");
        jMenuBar5.add(jMenu1);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("jMenu12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b4.setBackground(new java.awt.Color(0, 153, 153));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 44, -1));

        b5.setBackground(new java.awt.Color(0, 153, 153));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 44, -1));

        b6.setBackground(new java.awt.Color(0, 153, 153));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 44, -1));

        sub.setBackground(new java.awt.Color(0, 153, 153));
        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        jPanel1.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 54, -1));

        b7.setBackground(new java.awt.Color(0, 153, 153));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 44, -1));

        b8.setBackground(new java.awt.Color(0, 153, 153));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 44, -1));

        b9.setBackground(new java.awt.Color(0, 153, 153));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 44, -1));

        mul.setBackground(new java.awt.Color(0, 153, 153));
        mul.setText("*");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        jPanel1.add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 54, -1));

        CE.setBackground(new java.awt.Color(255, 102, 102));
        CE.setForeground(new java.awt.Color(255, 255, 255));
        CE.setText("C");
        CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEActionPerformed(evt);
            }
        });
        jPanel1.add(CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 40, -1));

        b0.setBackground(new java.awt.Color(0, 153, 153));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 44, -1));

        equals.setBackground(new java.awt.Color(0, 153, 153));
        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        jPanel1.add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 44, -1));

        div.setBackground(new java.awt.Color(0, 153, 153));
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 54, -1));

        sin.setBackground(new java.awt.Color(0, 153, 153));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        jPanel1.add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 54, -1));

        cos.setBackground(new java.awt.Color(0, 153, 153));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        jPanel1.add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 54, -1));

        tan.setBackground(new java.awt.Color(0, 153, 153));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        jPanel1.add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 54, -1));

        pow.setBackground(new java.awt.Color(0, 153, 153));
        pow.setText("x2");
        pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powActionPerformed(evt);
            }
        });
        jPanel1.add(pow, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 54, -1));
        jPanel1.add(pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 307, -1, 50));

        XpowY.setBackground(new java.awt.Color(0, 153, 153));
        XpowY.setText("X^Y");
        XpowY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XpowYActionPerformed(evt);
            }
        });
        jPanel1.add(XpowY, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 54, -1));

        fac.setBackground(new java.awt.Color(0, 153, 153));
        fac.setText("n!");
        fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facActionPerformed(evt);
            }
        });
        jPanel1.add(fac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 54, -1));

        pnt.setBackground(new java.awt.Color(0, 153, 153));
        pnt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnt.setText(".");
        pnt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pntActionPerformed(evt);
            }
        });
        jPanel1.add(pnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 44, -1));

        add.setBackground(new java.awt.Color(0, 153, 153));
        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 54, -1));

        b3.setBackground(new java.awt.Color(0, 153, 153));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 44, -1));

        b2.setBackground(new java.awt.Color(0, 153, 153));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 44, -1));

        b1.setBackground(new java.awt.Color(0, 153, 153));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 44, -1));

        log.setBackground(new java.awt.Color(0, 153, 153));
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 54, -1));

        Sqrt.setBackground(new java.awt.Color(0, 153, 153));
        Sqrt.setText("Sqrt");
        Sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtActionPerformed(evt);
            }
        });
        jPanel1.add(Sqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 54, -1));

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 282, 49));

        PI.setBackground(new java.awt.Color(0, 153, 153));
        PI.setText("PI");
        PI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIActionPerformed(evt);
            }
        });
        jPanel1.add(PI, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 54, -1));

        on.setBackground(new java.awt.Color(0, 153, 153));
        on.setText("on");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });
        jPanel1.add(on, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 54, -1));

        file.setText("File");

        Calculator.setText("Calculator");
        file.add(Calculator);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        file.add(Exit);

        jMenuBar1.add(file);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        //display.setText(b4.getText());
         String btn6Text = display.getText() + b4.getText();
        display.setText(btn6Text);
    }//GEN-LAST:event_b4ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
       
        
    }//GEN-LAST:event_displayActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
     
        String btnOneText = display.getText() + b1.getText();
        
        display.setText(btnOneText);
       
       
    
      
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
     
        
        String btntwoText = display.getText() + b2.getText();
        display.setText(btntwoText);
        
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         String btnthreeText = display.getText() + b3.getText();
        display.setText(btnthreeText);
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
 
         String btn5Text = display.getText() + b5.getText();
        display.setText(btn5Text);

    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
      
         String btn6Text = display.getText() + b6.getText();
        display.setText(btn6Text);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
      
         String btn7Text = display.getText() + b7.getText();
        display.setText(btn7Text);
       
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
 String btn8Text = display.getText() + b8.getText();
        display.setText(btn8Text);}
         //display.setText(b8.getText());    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       
         String btn9Text = display.getText() + b9.getText();
        display.setText(btn9Text);
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
 String btn0Text = display.getText() + b0.getText();
        display.setText(btn0Text);        
    }//GEN-LAST:event_b0ActionPerformed

    private void CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEActionPerformed
    total2=0;     
        display.setText("");   
    }//GEN-LAST:event_CEActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
      switch ( math_operator ) {
        case '+':
            total2 = total1 + Double.parseDouble(display.getText( ) );
        break;
        case '-':
            total2 = total1 - Double.parseDouble(display.getText( ) );
        break;
        case '/':
            total2 = total1 / Double.parseDouble(display.getText( ) );
        break;
        case '*':
            
            total2 = total1*Double.parseDouble(display.getText( ) );
           
        break;
        case 's':
          
            total2=java.lang.Math.sin(total1*(Math.PI/180.0));
            
            break;
              case 'c':
            total2=java.lang.Math.cos(total1*Math.PI/180.0);
            break;
                    case 't':
            total2=java.lang.Math.tan(total1*Math.PI/180.0);
            break;
                         case 'x':
                          total2=java.lang.Math.pow(total1,2);
            break;
            case 'l':
                          total2=java.lang.Math.log(total1);
            break;
                case 'S':
                          total2=java.lang.Math.sqrt(total1);
            break;
                     case 'X':
                          total2=total2+Double.parseDouble(display.getText( ));
                         
                          total2=java.lang.Math.pow(total1, total2);
                          
                          
                          
                          
            break;
                         case 'n':
                          total2=fact;
                          total3=0;
                          fact=1;
                         
            break;
        }
        
      
        display.setText( Double.toString(total2) );
        total1 = 0;
        
    
    }//GEN-LAST:event_equalsActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       String button_text = add.getText();
        getOperator(button_text);
        
    }//GEN-LAST:event_addActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       
         String button_text = sub.getText();
        getOperator(button_text);
    }//GEN-LAST:event_subActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
       
         String button_text = mul.getText();
        getOperator(button_text);
    }//GEN-LAST:event_mulActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
       
         String button_text = div.getText();
        getOperator(button_text);
    }//GEN-LAST:event_divActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
         
         String sinText =sin.getText();
       
        getOperator(sinText);
       
        
         
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        String cosText =cos.getText();
         
        getOperator(cosText); 
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
       String tanText =tan.getText();
         
        getOperator(tanText); 
    }//GEN-LAST:event_tanActionPerformed

    private void powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powActionPerformed
       String powbtn=pow.getText();
      
       getOperator(powbtn); 
       
       
    }//GEN-LAST:event_powActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
       String logbtn=log.getText();
       
       getOperator(logbtn); 
    }//GEN-LAST:event_logActionPerformed

    private void SqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtActionPerformed
       String Sqrtbtn=Sqrt.getText();
      
       getOperator(Sqrtbtn); 
    }//GEN-LAST:event_SqrtActionPerformed

    private void XpowYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XpowYActionPerformed
        
      
       String XpowYbtn=XpowY.getText();
       getOperator(XpowYbtn);
    }//GEN-LAST:event_XpowYActionPerformed

    private void facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facActionPerformed
      
      
        String fbtn=fac.getText();
      
       getOperator(fbtn);
    }//GEN-LAST:event_facActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
     
    }//GEN-LAST:event_ExitActionPerformed

    private void pntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pntActionPerformed
        // TODO add your handling code here:
                
        String btnpntText = display.getText() + pnt.getText();
        display.setText(btnpntText);
        
    }//GEN-LAST:event_pntActionPerformed

    private void PIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIActionPerformed
        // TODO add your handling code here:
        //display.setText(string.valueOf(Math.PI));
         String btnpntText = display.getText() + pnt.getText();
        display.setText(btnpntText);
        
    }//GEN-LAST:event_PIActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        // TODO add your handling code here:
            total2=0;     
        display.setText("");   
    }//GEN-LAST:event_onActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CalculatorApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CE;
    private javax.swing.JMenuItem Calculator;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton PI;
    private javax.swing.JButton Sqrt;
    private javax.swing.JButton XpowY;
    private javax.swing.JButton add;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton cos;
    private javax.swing.JTextField display;
    private javax.swing.JButton div;
    private javax.swing.JButton equals;
    private javax.swing.JButton fac;
    private javax.swing.JMenu file;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log;
    private javax.swing.JButton mul;
    private javax.swing.JButton on;
    private javax.swing.JLabel pic;
    private javax.swing.JButton pnt;
    private javax.swing.JButton pow;
    private javax.swing.JButton sin;
    private javax.swing.JButton sub;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables


 
    
}
